### ISSUE TITLE
nginx_installer ERROR: Command '['nginx', '-v']' returned non-zero exit status 1

### ISSUE THREAD

**Issue by leowmjw** [honeycombio/honey_installers#5]
Just trying out Honeycomb on Ubuntu 16.04 in Azure but encountered error :(

Python Version:
```
testadmin@acme-nomad-dev-director-node-1:~$ python -V
Python 2.7.12
```

Error (same error with or without sudo):
```
testadmin@acme-nomad-dev-director-node-1:~$ ./nginx_installer --writekey=ABXCCD
🐝 Honeytail nginx installer 1.42

[1/5] Checking for honeytail...
✔ Found usable honeytail binary (version 1.270)


[2/5] Gathering honeycomb account info...
✔ Great, found your team: nomad-box
Which Honeycomb dataset should we send events to? (It'll be created if it doesn't already exist) [Nginx]: 

[3/5] Logging fixes/suggestions...

[4/5] Locating log file...
Looking for nginx config...

✔ Found nginx config at /etc/nginx/nginx.conf

✔ Processing Nginx config: /etc/nginx/nginx.conf
Using log located at /var/log/nginx/access.log
Checking Permissions...
Traceback (most recent call last):
  File "nginx_installer.py", line 346, in <module>
  File "site-packages/click/core.py", line 716, in __call__
  File "site-packages/click/core.py", line 696, in main
  File "site-packages/click/core.py", line 889, in invoke
  File "site-packages/click/core.py", line 534, in invoke
  File "nginx_installer.py", line 342, in start
  File "honey_installer/installer.py", line 477, in start
  File "honey_installer/installer.py", line 426, in locate_log_file
  File "nginx_installer.py", line 96, in find_log_file
  File "nginx_installer.py", line 325, in _get_nginx_version
  File "subprocess.py", line 573, in check_output
subprocess.CalledProcessError: Command '['nginx', '-v']' returned non-zero exit status 1
Failed to execute script nginx_installer

```

Nginx version installed:
```
testadmin@acme-nomad-dev-director-node-1:~$ nginx -v
nginx version: nginx/1.10.0 (Ubuntu)
```

**Comment by toshok** [comment]
This is the same problem as was fix for our `subprocess.Popen` usage.  The problem for ubuntu 16.04 is:

```
nginx: /tmp/_MEIep9Xfh/libssl.so.1.0.0: version `OPENSSL_1.0.2' not found (required by nginx)
nginx: /tmp/_MEIep9Xfh/libcrypto.so.1.0.0: version `OPENSSL_1.0.2' not found (required by nginx)
```

note the `/tmp`'s.  that suggests that we're running system nginx with our `LD_LIBRARY_PATH` in effect, and nginx is trying to use the .so's pyinstaller includes in our binaries.
